
export const Images = {
    logo: require("../assets/logo.png"),
    fbLogo: require("../assets/facebook.png"),
    googleLogo: require("../assets/google.png"),
    gitHubLogo: require("../assets/github.png"),
    linkedInLogo: require("../assets/linkedIn.png"),
    avartar: require("../assets/avartar.jpg"),
    heart: require("../assets/heartBeat.png"),
    temperature: require("../assets/temperature.png"),
    settings: require("../assets/settings.png"),
    addChildTracker: require("../assets/parrentsWirhChild.png"),
    availableChileTrack: require("../assets/trackChild.png"),
    profile: require("../assets/profile.png"),
    group: require("../assets/group.png"),
    aboutUs: require("../assets/aboutUs.jpg"),
    childAvartar: require("../assets/childAvartar.png"),
    profileBg: require("../assets/profileImageBackground.jpg"),
    email: require("../assets/email.png"),
    phone: require("../assets/phone.png"),
    star: require("../assets/star.png"),
    creategroup: require("../assets/creategroup.png"),
    groupbg: require("../assets/groupbg.png"),
    watche1: require("../assets/watch-1.png"),
    watche2: require("../assets/watch-2.png"),
    watche3: require("../assets/watch-3.png"),

};
